import { EnumTypeCard, type ICard } from '../../types/card.types.ts';

export const CARDS: ICard[] = [
    {
        name: 'HTML',
        mana: 1,
        attack: 1,
        health: 1,
        imageUrl: '/assets/cards/html.png',
    },
    {
        name: 'CSS',
        mana: 1,
        attack: 1,
        health: 2,
        imageUrl: '/assets/cards/css.png',
    },
    {
        name: 'Tailwind CSS',
        mana: 1,
        attack: 2,
        health: 1,
        imageUrl: '/assets/cards/tailwind.png',
    },
    {
        name: 'Webpack',
        mana: 2,
        attack: 2,
        health: 2,
        imageUrl: '/assets/cards/webpack.png',
    },
    {
        name: 'JavaScript',
        mana: 2,
        attack: 3,
        health: 2,
        imageUrl: '/assets/cards/js.png',
    },
    {
        name: 'Vs Code',
        mana: 2,
        attack: 2,
        health: 4,
        imageUrl: '/assets/cards/vs-code.png',
    },
    {
        name: 'Webstorm',
        mana: 2,
        attack: 3,
        health: 3,
        imageUrl: '/assets/cards/webstorm.png',
    },
    {
        name: 'Node.js',
        mana: 3,
        attack: 3,
        health: 4,
        imageUrl: '/assets/cards/node.png',
    },
    {
        name: 'Redux',
        mana: 3,
        attack: 5,
        health: 2,
        imageUrl: '/assets/cards/redux.png',
    },
    {
        name: 'Svelte',
        mana: 3,
        attack: 4,
        health: 3,
        imageUrl: '/assets/cards/svelte.png',
    },
    {
        name: 'Vue',
        mana: 3,
        attack: 1,
        health: 6,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/vue.png',
    },
    {
        name: 'React',
        mana: 3,
        attack: 2,
        health: 5,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/react.png',
    },
    {
        name: 'Nginx',
        mana: 4,
        attack: 5,
        health: 4,
        imageUrl: '/assets/cards/nginx.png',
    },
    {
        name: 'Gatsby',
        mana: 4,
        attack: 4,
        health: 5,
        imageUrl: '/assets/cards/gatsby.png',
    },
    {
        name: 'Astro',
        mana: 4,
        attack: 6,
        health: 3,
        imageUrl: '/assets/cards/astro.png',
    },
    {
        name: 'Nuxt.js',
        mana: 4,
        attack: 3,
        health: 6,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/nuxt.png',
    },
    {
        name: 'TypeScript',
        mana: 5,
        attack: 6,
        health: 4,
        imageUrl: '/assets/cards/ts.png',
    },
    {
        name: 'Next.js',
        mana: 5,
        attack: 7,
        health: 3,
        imageUrl: '/assets/cards/next.png',
    },
    {
        name: 'Prisma',
        mana: 5,
        attack: 4,
        health: 7,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/prisma.png',
    },
    {
        name: 'Nest.js',
        mana: 5,
        attack: 5,
        health: 5,
        imageUrl: '/assets/cards/nest-js.png',
    },
    {
        name: 'Three js',
        mana: 6,
        attack: 8,
        health: 3,
        imageUrl: '/assets/cards/three-js.png',
    },
    {
        name: 'Bootstrap',
        mana: 6,
        attack: 5,
        health: 7,
        imageUrl: '/assets/cards/bootstrap.png',
    },
    {
        name: 'SCSS',
        mana: 5,
        attack: 4,
        health: 8,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/scss.png',
    },
    {
        name: 'Gulp',
        mana: 5,
        attack: 6,
        health: 5,
        imageUrl: '/assets/cards/gulp.png',
    },
    {
        name: 'Backbone.js',
        mana: 6,
        attack: 7,
        health: 5,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/backbone.png',
    },
    {
        name: 'Foundation',
        mana: 5,
        attack: 3,
        health: 9,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/foundation.png',
    },
    {
        name: 'Ember.js',
        mana: 6,
        attack: 5,
        health: 9,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/ember.png',
    },
    {
        name: 'Alpine.js',
        mana: 3,
        attack: 6,
        health: 4,
        imageUrl: '/assets/cards/alpine.png',
    },
    {
        name: 'D3.js',
        mana: 3,
        attack: 2,
        health: 8,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/d3.png',
    },
    {
        name: 'Preact',
        mana: 2,
        attack: 4,
        health: 1,
        imageUrl: '/assets/cards/preact.png',
    },
    {
        name: 'Electron',
        mana: 2,
        attack: 5,
        health: 2,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/electron.png',
    },
    {
        name: 'Lit',
        mana: 2,
        attack: 3,
        health: 5,
        imageUrl: '/assets/cards/lit.png',
    },
    {
        name: 'Vite',
        mana: 2,
        attack: 4,
        health: 3,
        imageUrl: '/assets/cards/vite.png',
    },
    {
        name: 'Stencil',
        mana: 2,
        attack: 3,
        health: 6,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/stencil.png',
    },
    {
        name: 'Storybook',
        mana: 2,
        attack: 5,
        health: 3,
        imageUrl: '/assets/cards/storybook.png',
    },
    {
        name: 'Grunt',
        mana: 2,
        attack: 1,
        health: 7,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/grunt.png',
    },
    {
        name: 'Handlebars',
        mana: 2,
        attack: 2,
        health: 1,
        imageUrl: '/assets/cards/handlebars.png',
    },
    {
        name: 'Firebase',
        mana: 2,
        attack: 4,
        health: 5,
        imageUrl: '/assets/cards/firebase.png',
    },
    {
        name: 'GraphQL',
        mana: 2,
        attack: 2,
        health: 3,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/graphQL.png',
    },
    {
        name: 'Zustand',
        mana: 2,
        attack: 1,
        health: 3,
        imageUrl: '/assets/cards/zustand.png',
    },
    {
        name: 'WordPress',
        mana: 2,
        attack: 3,
        health: 1,
        imageUrl: '/assets/cards/wp.png',
    },
    {
        name: 'MobX',
        mana: 2,
        attack: 1,
        health: 4,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/mobX.png',
    },
    {
        name: 'PHP',
        mana: 2,
        attack: 1,
        health: 8,
        type: EnumTypeCard.taunt,
        imageUrl: '/assets/cards/php.png',
    },
];
